# Generated by Django 5.2.7 on 2025-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='retreat/about/')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RetreatFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RetreatHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='retreat/hero/')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetreatOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='retreat/offers/')),
                ('title', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RetreatTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='retreat/testimonials/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('testimonial', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_user_submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
